routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index');

Route::get('/pages/detail/{id}', 'PageController@detail')->name('page.detail');;
Route::get('/product/detail/{id}', 'ProductController@detail')->name('product.detail');;
Route::get('/product/view', 'ProductController@view')->name('product.view');;
Route::get('/cart/view', 'CartController@view')->name('cart.view');;


Route::resource('cart','CartController');//resource route
Route::resource('sliders','SliderController');//resource route
//Route::get('/sliders','SliderController@index');
//Route::get('/sliders.create','SliderController@create');
//Route::get('/slider-detail/{id}','SliderController@show');
Route::resource('category', 'CategoryController');
Route::resource('product', 'ProductController');
Route::resource('staticblock', 'StaticblockController');
Route::resource('review', 'ReviewController');
Route::resource('picture', 'PictureController');
Route::resource('subscriber', 'SubscriberController');
Route::resource('page', 'PageController');

//Route::get('/categories','CategoryController@index');
//Route::get('/product','ProductController@index');



//////////////////////////////////

Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/404', function () {
    return view('404');
});
Route::get('/gallery-post', function () {
    return view('gallery-post');
});
///////////////////
Route::get('/gggallery-post', function () {
    return view('gggallery-post');
});
Route::get('/grid', function () {
    return view('grid');
});
Route::get('/listing-with-sidbar', function () {
    return view('listing-with-sidbar');
});
Route::get('/listing-without-sidbar', function () {
    return view('listing-without-sidbar');
});
Route::get('/masonry', function () {
    return view('masonry');
});
Route::get('/standart-post', function () {
    return view('standart-post');
});
Route::get('/text-post', function () {
    return view('text-post');
});
Route::get('/video-post', function () {
    return view('video-post');
});
Route::get('/cart-1', function () {
    return view('cart-1');
});
Route::get('/cart-2', function () {
    return view('cart-2');
});
Route::get('/checkout-1', function () {
    return view('checkout-1');
});
Route::get('/checkout-2', function () {
    return view('checkout-2');
});
Route::get('/coming-soon', function () {
    return view('coming-soon');
});
Route::get('/compare', function () {
    return view('compare');
});
Route::get('/contacts', function () {
    return view('contacts');
});
Route::get('/elements-accordion', function () {
    return view('elements-accordion');
});
Route::get('/elements-banners', function () {
    return view('elements-banners');
});
Route::get('/elements-buttons', function () {
    return view('elements-buttons');
});
Route::get('/elements-icon-box', function () {
    return view('elements-icon-box');
});
Route::get('/elements-maps', function () {
    return view('elements-maps');
});
Route::get('/elements-product', function () {
    return view('elements-product');
});
Route::get('/elements-progress-bar', function () {
    return view('elements-progress-bar');
});
Route::get('/elements-social', function () {
    return view('elements-social');
});
Route::get('/elements-tabs', function () {
    return view('elements-tabs');
});
Route::get('/elements-toggles', function () {
    return view('elements-toggles');
});
Route::get('/elements-typography', function () {
    return view('elements-typography');
});
Route::get('/empty-category', function () {
    return view('empty-category');
});
Route::get('/empty-compare', function () {
    return view('empty-compare');
});
Route::get('/empty-search', function () {
    return view('empty-search');
});
Route::get('/empty-shopping-cart', function () {
    return view('empty-shopping-cart');
});
Route::get('/empty-wishlist', function () {
    return view('empty-wishlist');
});
Route::get('/faq', function () {
    return view('faq');
});
Route::get('/gallery', function () {
    return view('gallery');
});
Route::get('/gallery-3-thumbs', function () {
    return view('gallery-3-thumbs');
});
Route::get('/gallery-4-thumbs', function () {
    return view('gallery-4-thumbs');
});
Route::get('/gallery-masonry', function () {
    return view('gallery-masonry');
});
Route::get('/index', function () {
    return view('index');
});
Route::get('/index-02', function () {
    return view('index-02');
});
Route::get('/index-03', function () {
    return view('index-03');
});
Route::get('/index-04', function () {
    return view('index-04');
});
Route::get('/index-05', function () {
    return view('index-05');
});
Route::get('/index-06', function () {
    return view('index-06');
});
Route::get('/index-07', function () {
    return view('index-07');
});
Route::get('/index-08', function () {
    return view('index-08');
});
Route::get('/index-09', function () {
    return view('index-09');
});
Route::get('/index-10', function () {
    return view('index-10');
});
Route::get('/index-11', function () {
    return view('index-11');
});
Route::get('/index-12', function () {
    return view('index-12');
});
Route::get('/listing', function () {
    return view('listing');
});
Route::get('/listing-big-reviews', function () {
    return view('listing-big-reviews');
});
Route::get('/listing-catalogue', function () {
    return view('listing-catalogue');
});
Route::get('/listing-collections', function () {
    return view('listing-collections');
});
Route::get('/listing-fullwidth', function () {
    return view('listing-fullwidth');
});
Route::get('/listing-right-sidebar', function () {
    return view('listing-right-sidebar');
});
Route::get('/listing-with-custom-html-block', function () {
    return view('listing-with-custom-html-block');
});
Route::get('/listing-without-columns', function () {
    return view('listing-without-columns');
});
Route::get('/listing-with-sidebar', function () {
    return view('listing-with-sidebar');
});
Route::get('/login', function () {
   return view('login');
});


Route::get('/my-account', function () {
    return view('my-account');
});
//Route::get('/product', function () {
   // return view('product');
//});
Route::get('/product-grouped', function () {
    return view('product-grouped');
});
Route::get('/product-on-sale', function () {
    return view('product-on-sale');
});
Route::get('/product-out-of-stock', function () {
    return view('product-out-of-stock');
});

Route::get('/product-simple-variant-1', function () {
    return view('product-simple-variant-1');
});
Route::get('/product-simple-variant-2', function () {
    return view('product-simple-variant-2');
});
Route::get('/product-variable', function () {
    return view('product-variable');

});
Route::get('/register', function () {
    return view('register');
});
//Route::get('/services', function () {
   // return view('services');
//});
//Route::get('/sitemap', function () {
    //return view('sitemap');
//});
//Route::get('/wishlist', function () {
   // return view('wishlist');
//});

Auth::routes();

Route::get('/home','HomeController@index')->name('home');

app/Subscriber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    //
}

app/Http/Controllers/SubscriberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subscriber;
class SubscriberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $subscribers = Subscriber::all();
        return view('subscriber.index',compact('subscribers'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subscriber.subscriber');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'mail'=>'required',

        ]);

        $subscriber = new Subscriber;
        $subscriber->mail = $request->mail;
        $subscriber->save();


        return redirect(route('subscriber.index'))->withMessage('Subscriber Added');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $subscriber = Subscriber::find($id);
        return view('subscriber.show')->with('subscriber',$subscriber);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subscriber = Subscriber::where('id',$id)->first();
        return view('subscriber.edit',compact('subscriber'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[

            'mail'=>'required',

        ]);

        $subscriber = Subscriber::find($id);
        $subscriber->mail= $request->mail;
        $subscriber->save();

        return redirect(route('subscriber.index'))->withMessage('Subscriber Is Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Subscriber::where('id',$id)->delete();
        return redirect()->back()->withMessage('Subscriber Is Deleted');
    }
}

resources/views/subscriber/edit.blade.php
@extends('layouts/mogo')

@section('main_content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                    <div class="panel-heading"><h5 style="text-align: center">Subscriber Edit Form</h5></div>


                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('subscriber.update',$subscriber->id) }}" >
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            
                             <div class="form-group">
                                <label for="mail" class="col-md-4 control-label">HTML_block</label>

                                <div class="col-md-6">
                                    <input id="mail" type="text" class="form-control" name="mail" value="{{ $subscriber->mail }}" >
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>

                                    <a href="{{ route('subscriber.create') }}" class=" btn btn-danger">Create</a>
                                    <a href="{{ route('subscriber.index') }}" class=" btn btn-danger">subscriber</a>
                                </div>
                            </div>
                        </form>
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/subscriber/index.blade.php
@extends('layouts/mogo')

@section('main_content')
    <div class="panel-heading">
        <h5 style="text-align: center">Subscriber Lists <a href="{{ route('subscriber.create') }}" class=" btn btn-danger pull-right">Add New Subscriber</a></h5>
        <h5 >{{ session('message') }}</h5>


    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>S.No</th>
            <th>Mail</th>
            <th>Action</th>

        </tr>
        </thead>
        <tbody>

        @foreach($subscribers as $subscriber)

            <tr>
                <td>{{ $loop->index + 1}}</td>
                <td>{{ $subscriber->mail}}</td>
                <td> <a href="{{ route('subscriber.show',$subscriber->id) }}" class=" btn btn-danger"><span class=" glyphicon glyphicon-eye-open"></span></a>
                    <a href="{{ route('subscriber.edit',$subscriber->id) }}" class=" btn btn-info"><span class="glyphicon glyphicon-edit"></span></a>
                    <form id="delete-form-{{ $subscriber->id }}" method="POST" action="{{ route('subscriber.destroy',$subscriber->id) }}" style="display: none">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                            if(confirm('Are you sure, You went to delete this?'))

                            {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $subscriber->id }}').submit();
                            }
                            else{
                            event.preventDefault();
                            }
                            " class=" btn btn-info"><span class="glyphicon glyphicon-trash"></span></a>

                </td>


            </tr>
        @endforeach

        </tbody>
        <tfoot>
        <tr>
            <th>S.No</th>

            <th>Mail</th>
            <th>Action</th>



        </tr>
        </tfoot>
    </table>



@endsection

resources/views/subscriber/show.blade.php
@extends('layouts/mogo')

@section('main_content')
       <div class="container">
              <div class="row">
                     <div class="col-md-10 col-md-offset-2">


                                   <div class="panel-heading ">
                                          <h5 style="text-align: center">Subscriber Details
                                                 <a href="{{ route('subscriber.create') }}" class=" btn btn-danger pull-right">Create</a>
                                                 <a href="{{ route('subscriber.index') }}" class=" btn btn-danger pull-right">Subscriber</a>
                                          </h5>

                                   </div>


                                   <div> <b>Mail:-</b>   {{ $subscriber->mail}}</div>



                   </div>

              </div>
       </div>





@endsection

resources/views/subscriber/subscriber.blade.php
@extends('layouts/mogo')

@section('main_content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                    <div class="panel-heading"><h3 style="text-align: center">Subscriber Create Form</h3>
                    </div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('subscriber.store') }}">
                            {{ csrf_field() }}

                             <div class="form-group">
                                <label for="mail" class="col-md-4 control-label">Mail</label>

                                <div class="col-md-6">
                                    <input id="mail" type="text" class="form-control" name="mail" >
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('subscriber.index') }}" class=" btn btn-danger">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>

            </div>
        </div>
    </div>
@endsection